### ISSUE TITLE
add support for cloud providers

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/jellyfish-fog#1]
Actionable Items:
- [x] Add [support](https://github.com/projectjellyfish/jellyfish-fog/issues/17) for AWS
  - [x] [Remove Hardcoded AMI for EC2](https://github.com/projectjellyfish/jellyfish-fog/issues/6)
- [x] Add [support](https://github.com/projectjellyfish/jellyfish-fog/issues/12) for VMware
- [x] Add [support](https://github.com/projectjellyfish/jellyfish-fog/issues/10) for Azure
- [ ] Add support for Digital Ocean 
- [x] Verify provisioner ~ _[moved](https://github.com/projectjellyfish/jellyfish-fog/issues/18)_
- [x] Refactor [product types](https://github.com/projectjellyfish/api/issues/581) into api
- [x] Add specs back into repo that can be run via `rake`

> Follow-up
> - soft typing: when a provisioner is enabled then certain key words in a product name will cause it to be routed to the associated provisioner as opposed to NullProvisioner on checkout
> - `rake jobs:work`: this command will hang if the AWS entity being provisioned is killed during pending state and require a [SIGKILL](http://askubuntu.com/questions/59811/kill-pid-not-really-killing-the-process-why) to remove.

**Comment by chriskacerguis** [comment]
Updated first ticket update (removed Google, added VMware)

**Comment by mafernando** [comment]
References:
- [Fog RubyDocs](http://www.rubydoc.info/github/fog/fog-aws/Fog)
- [Fog Compute](https://github.com/fog/fog-core/blob/master/lib/fog/compute.rb)

**Comment by mafernando** [comment]
See [here](http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula) for how to downgrade phantomjs to 1.9.8 for feature specs to pass

**Comment by mafernando** [comment]
**AWS To Do:**
- Add ability to provision greater than t1.micros

**Comment by mafernando** [comment]
**Azure To Do:**
  - Add ability to provision VM 
    - Can provision in mock mode, but attempts to provision on Azure IRL are not working because of the consistently occurring error: `The virtual machine image source is not valid.`
    - Azure doesn't provide your user access to default VM images that are provisionable via API, instead you need to create a VM through the [Azure Management Portal](https://manage.windowsazure.com). (_**trying to figure out this part out**_) Then you can generate a VM image from that instance which you can add to your accounts list of provisionable images via API. THEN you use the image ID to provision via Azure Ruby SDK.
  - Add ability to provision Storage
  - Add ability to provision Databases

### Investigating how to setup image id 

**Choose selection from Azure Image Gallery:**
http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-create-custom/

**Login to the VM to prep it for cloning:**
http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-how-to-log-on/

**Template the VM to use as a base for clones:**
http://blogs.technet.com/b/keithmayer/archive/2013/01/17/step-by-step-templating-vms-in-the-cloud-with-windows-azure-and-powershell-31-days-of-servers-in-the-cloud-part-17-of-31.aspx

**Comment by mafernando** [comment]
RubyGems Repo: https://rubygems.org/gems/jellyfish-fog

**Comment by mafernando** [comment]
Gem Commit History:
- 0.0.2: 2e08932ba61175001076848df9e3d7ae3b5b0b95 - Adds vmware inf support
- 0.0.3: 0cbb803e0fa93ca93b33feacfb501b8e93d7a4d8 - Fixes how vmware payload response is stored
- 0.0.4: 2a8b01da10b84e7daa1a033b8e0d89a7c30dda69 - Adds ability to provision Azure infrastructure clone
- 0.0.5: 03b778e5877aed42f8ccdbe2e656b3ab089d8bf6 - adds ability to provision AWS VPCs, subnets, security groups, and EBS. Also cleans up how aws infrastructure, database, and storage stores payload response.
